import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'ENU' | 'PTB' | 'ESP' | 'FRA' | 'GER' | 'JPN' | 'ITA' | 'RUS' | 'ARA' | 'KOR'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys
const translations = {
  ENU: {
    // Main Menu Items
    'students': 'Students',
    'teachers': 'Teachers',
    'championships': 'Championships',
    'classes': 'Classes',
    'fight-plans': 'Fight Plans',
    'fight-modalities': 'Fight Modalities',
    'modality-registration': 'Modality Registration',
    'modality-management': 'Modality Management',
    'modality-name': 'Modality Name',
    'modality-description': 'Description',
    'modality-type': 'Modality Type',
    'modality-level': 'Level',
    'modality-duration': 'Duration (minutes)',
    'modality-active': 'Active',
    'quality-evaluation': 'Quality & Evaluation',
    'branches': 'Branches',
    'schedules-checkins': 'Schedules & Check-Ins',
    'administration': 'Administration',
    
    // Students Sub-items
    'student-registration': 'Student Registration',
    'student-profiles': 'Student Profiles',
    'modality-by-student': 'FIGHT TRAINING PLAN',
    'student-evaluation': 'Student Evaluation & Grades',
    'student-attendance': 'Student Attendance',
    
    // Teachers Sub-items
    'teacher-registration': 'Teacher Registration',
    'teacher-profiles': 'Teacher Profiles',
    'assign-teachers': 'Assign Teachers to Classes',
    'teacher-evaluations': 'Teacher Evaluations',
    
    // Championships Sub-items
    'championship-registration': 'Championship Registration',
    'student-enrollment': 'Student Enrollment in Championships',
    'championship-results': 'Championship Results',
    'ranking-statistics': 'Ranking & Statistics',
    
    // Classes Sub-items
    'class-setup': 'Class Setup by Modality',
    'schedule-management': 'Schedule Management',
    'check-in-attendance': 'Check-In / Attendance Tracking',
    'class-capacity': 'Class Capacity & Limits',
    
    // Fight Plans Sub-items
    'plan-templates': 'Plan Templates',
    'assign-plans': 'Assign Plans to Students',
    'training-phases': 'Training Phases & Milestones',
    
    // Quality & Evaluation Sub-items
    'progress-reports': 'Student Progress Reports',
    'teacher-feedback': 'Teacher Feedback',
    'fitness-tests': 'Fitness Tests & Metrics',
    
    // Branches Sub-items
    'branch-registration': 'Branch Registration',
    'branch-details': 'Branch Details (location, contact)',
    'assign-branch': 'Assign Students/Teachers per Branch',
    'branch-schedules': 'Branch Schedules',
    'branch-facilities': 'Branch Facilities',
    'branch-reports': 'Branch Reports',
    
    // Schedules & Check-Ins Sub-items
    'weekly-timetable': 'Weekly Timetable',
    'booking-system': 'Student Booking System',
    'attendance-log': 'Real-Time Attendance Log',
    
    // Administration Sub-items
    'user-profiles': 'User Profiles & Roles',
    'language-selector': 'Language Selector',
    'app-settings': 'App Settings',
    
    // Common
    'dashboard': 'Dashboard',
    'academy-manager': 'Academy Manager',
    'management-system': 'Management System',
    'welcome-message': 'Welcome to your Jiu-Jitsu Academy Management System - Modern UI Deployed! 🚀',
    'total-students': 'Total Students',
    'active-students': 'Active Students',
    'black-belts': 'Black Belts',
    'belt-level-counts': 'Belt Level Counts',
    'white-belts': 'White Belts',
    'blue-belts': 'Blue Belts',
    'purple-belts': 'Purple Belts',
    'brown-belts': 'Brown Belts',
    'export-to-excel': 'Export to Excel',
    'export-students': 'Export Students',
    'import-from-excel': 'Import from Excel',
    'import-students': 'Import Students',
    'select-excel-file': 'Select Excel File',
    'import-success': 'Import Successful',
    'import-error': 'Import Error',
    'imported-students': 'Imported Students',
    'import-summary': 'Import Summary',
    'file-format-help': 'File Format Help',
    'download-template': 'Download Template',
    'filter-students': 'Filter Students',
    'search-students': 'Search Students',
    'filter-by-belt': 'Filter by Belt',
    'filter-by-gender': 'Filter by Gender',
    'filter-by-status': 'Filter by Status',
    'all-belts': 'All Belts',
    'all-genders': 'All Genders',
    'all-status': 'All Status',
    'clear-filters': 'Clear Filters',
    'active-only': 'Active Only',
    'inactive-only': 'Inactive Only',
    'student-modality-management': 'Student Modality Management',
    'student-modality-connections': 'Student Modality Connections',
    'assign-modalities': 'Assign Modalities',
    'student-modality': 'Student Modality',
    'assigned-modalities': 'Assigned Modalities',
    'modality-assignment': 'Modality Assignment',
    'select-student': 'Select Student',
    'select-modalities': 'Select Modalities',
    'assignment-date': 'Assignment Date',
    'instructors': 'Instructors',
    'recent-activity': 'Recent Activity',
    'no-recent-activity': 'No recent activity',
    'start-adding': 'Start by adding students or instructors',
    'quick-actions': 'Quick Actions',
    'add-new-student': 'Add New Student',
    'add-new-instructor': 'Add New Instructor',
    'add-martial-art-type': 'Add Martial Art Type',
    'welcome-admin': 'Welcome back, Admin',
    'language': 'Language',
    'select-language': 'Select Language',
    'portuguese': 'Portuguese',
    'english': 'English',
    'save-settings': 'Save Settings',
    'settings-saved': 'Settings saved successfully!',
    
    // Dashboard specific
    'total-students': 'Total Students',
    'instructors': 'Instructors',
    'fight-modalities': 'Fight Modalities',
    'classes-today': 'Classes Today',
    'total-check-ins': 'Total Check-ins',
    'branches': 'Branches',
    'training-plans': 'Training Plans',
    'recent-activity': 'Recent Activity',
    'quick-actions': 'Quick Actions',
    'add-new-student': 'Add New Student',
    'add-new-instructor': 'Add New Instructor',
    'create-class-schedule': 'Create Class Schedule',
    'check-in-student': 'Check-In Student',
    'active': 'active',
    'active-teachers': 'Active teachers',
    'available-styles': 'Available styles',
    'total-active': 'total active',
    'this-week': 'this week',
    'facilities': 'facilities',
    'active-plans': 'active',
    'last-7-days': 'Last 7 days',
    'check-ins-this-week': 'check-ins this week',
    'students-actively-training': 'Students actively training',
    'classes-scheduled-today': 'classes scheduled today',
    'active-class-schedule': 'Active class schedule',
    'active-training-plans': 'active training plans',
    'students-with-ongoing-programs': 'Students with ongoing programs',
    
    // Sidebar specific
    'teachers-instructors': 'Teachers & Instructors',
    'class-schedules': 'Class Schedules',
    'user-profiles': 'User Profiles',
    'company-info-settings': 'Company Info & Settings',
    'language-settings': 'Language Settings',
    'app-settings': 'App Settings',
    
    // Student specific
    'preferred-language': 'Preferred Language for Interactions',
    'preferred-language-help': 'Language used for WhatsApp notifications and system communications'
  },
  PTB: {
    // Main Menu Items
    'students': 'Alunos',
    'teachers': 'Professores',
    'championships': 'Campeonatos',
    'classes': 'Turmas',
    'fight-plans': 'Planos de Luta',
    'fight-modalities': 'Modalidades de Luta',
    'modality-registration': 'Cadastro de Modalidades',
    'modality-management': 'Gestão de Modalidades',
    'modality-name': 'Nome da Modalidade',
    'modality-description': 'Descrição',
    'modality-type': 'Tipo de Modalidade',
    'modality-level': 'Nível',
    'modality-duration': 'Duração (minutos)',
    'modality-active': 'Ativo',
    'quality-evaluation': 'Qualidade & Avaliação',
    'branches': 'Filiais',
    'schedules-checkins': 'Agenda & Check-Ins',
    'administration': 'Administração',
    
    // Students Sub-items
    'student-registration': 'Cadastro de Alunos',
    'student-profiles': 'Perfis dos Alunos',
    'modality-by-student': 'PLANO DE TREINAMENTO DE LUTA',
    'student-evaluation': 'Avaliação e Notas dos Alunos',
    'student-attendance': 'Frequência dos Alunos',
    
    // Teachers Sub-items
    'teacher-registration': 'Cadastro de Professores',
    'teacher-profiles': 'Perfis dos Professores',
    'assign-teachers': 'Atribuir Professores às Aulas',
    'teacher-evaluations': 'Avaliações dos Professores',
    
    // Championships Sub-items
    'championship-registration': 'Cadastro de Campeonatos',
    'student-enrollment': 'Inscrição de Alunos em Campeonatos',
    'championship-results': 'Resultados de Campeonatos',
    'ranking-statistics': 'Ranking e Estatísticas',
    
    // Classes Sub-items
    'class-setup': 'Configuração de Aulas por Modalidade',
    'schedule-management': 'Gestão de Horários',
    'check-in-attendance': 'Check-In / Controle de Frequência',
    'class-capacity': 'Capacidade e Limites das Aulas',
    
    // Fight Plans Sub-items
    'plan-templates': 'Modelos de Planos',
    'assign-plans': 'Atribuir Planos aos Alunos',
    'training-phases': 'Fases de Treinamento e Marcos',
    
    // Quality & Evaluation Sub-items
    'progress-reports': 'Relatórios de Progresso dos Alunos',
    'teacher-feedback': 'Feedback dos Professores',
    'fitness-tests': 'Testes de Condicionamento e Métricas',
    
    // Branches Sub-items
    'branch-registration': 'Cadastro de Filiais',
    'branch-details': 'Detalhes da Filial (localização, contato)',
    'assign-branch': 'Atribuir Alunos/Professores por Filial',
    'branch-schedules': 'Horários da Filial',
    'branch-facilities': 'Instalações da Filial',
    'branch-reports': 'Relatórios da Filial',
    
    // Schedules & Check-Ins Sub-items
    'weekly-timetable': 'Cronograma Semanal',
    'booking-system': 'Sistema de Reservas dos Alunos',
    'attendance-log': 'Log de Frequência em Tempo Real',
    
    // Administration Sub-items
    'user-profiles': 'Perfis de Usuário e Funções',
    'language-selector': 'Seletor de Idioma',
    'app-settings': 'Configurações do App',
    
    // Common
    'dashboard': 'Painel',
    'academy-manager': 'Gerenciador da Academia',
    'management-system': 'Sistema de Gestão',
    'welcome-message': 'Bem-vindo ao seu Sistema de Gestão da Academia de Jiu-Jitsu - UI Moderna Implantada! 🚀',
    'total-students': 'Total de Alunos',
    'active-students': 'Alunos Ativos',
    'black-belts': 'Faixas Pretas',
    'belt-level-counts': 'Contagem por Faixa',
    'white-belts': 'Faixas Brancas',
    'blue-belts': 'Faixas Azuis',
    'purple-belts': 'Faixas Roxas',
    'brown-belts': 'Faixas Marrons',
    'export-to-excel': 'Exportar para Excel',
    'export-students': 'Exportar Alunos',
    'import-from-excel': 'Importar do Excel',
    'import-students': 'Importar Alunos',
    'select-excel-file': 'Selecionar Arquivo Excel',
    'import-success': 'Importação Bem-sucedida',
    'import-error': 'Erro na Importação',
    'imported-students': 'Alunos Importados',
    'import-summary': 'Resumo da Importação',
    'file-format-help': 'Ajuda com Formato do Arquivo',
    'download-template': 'Baixar Modelo',
    'filter-students': 'Filtrar Alunos',
    'search-students': 'Buscar Alunos',
    'filter-by-belt': 'Filtrar por Faixa',
    'filter-by-gender': 'Filtrar por Gênero',
    'filter-by-status': 'Filtrar por Status',
    'all-belts': 'Todas as Faixas',
    'all-genders': 'Todos os Gêneros',
    'all-status': 'Todos os Status',
    'clear-filters': 'Limpar Filtros',
    'active-only': 'Apenas Ativos',
    'inactive-only': 'Apenas Inativos',
    'student-modality-management': 'Gestão de Modalidades por Aluno',
    'student-modality-connections': 'Conexões de Modalidades por Aluno',
    'assign-modalities': 'Atribuir Modalidades',
    'student-modality': 'Modalidade do Aluno',
    'assigned-modalities': 'Modalidades Atribuídas',
    'modality-assignment': 'Atribuição de Modalidade',
    'select-student': 'Selecionar Aluno',
    'select-modalities': 'Selecionar Modalidades',
    'assignment-date': 'Data de Atribuição',
    'instructors': 'Instrutores',
    'recent-activity': 'Atividade Recente',
    'no-recent-activity': 'Nenhuma atividade recente',
    'start-adding': 'Comece adicionando alunos ou instrutores',
    'quick-actions': 'Ações Rápidas',
    'add-new-student': 'Adicionar Novo Aluno',
    'add-new-instructor': 'Adicionar Novo Instrutor',
    'add-martial-art-type': 'Adicionar Tipo de Arte Marcial',
    'welcome-admin': 'Bem-vindo de volta, Admin',
    'language': 'Idioma',
    'select-language': 'Selecionar Idioma',
    'portuguese': 'Português',
    'english': 'Inglês',
    'save-settings': 'Salvar Configurações',
    'settings-saved': 'Configurações salvas com sucesso!',
    
    // Dashboard specific
    'total-students': 'Total de Alunos',
    'instructors': 'Instrutores',
    'fight-modalities': 'Modalidades de Luta',
    'classes-today': 'Aulas Hoje',
    'total-check-ins': 'Total de Check-ins',
    'branches': 'Filiais',
    'training-plans': 'Planos de Treino',
    'recent-activity': 'Atividade Recente',
    'quick-actions': 'Ações Rápidas',
    'add-new-student': 'Adicionar Novo Aluno',
    'add-new-instructor': 'Adicionar Novo Instrutor',
    'create-class-schedule': 'Criar Horário de Aula',
    'check-in-student': 'Check-in do Aluno',
    'active': 'ativo',
    'active-teachers': 'Professores ativos',
    'available-styles': 'Estilos disponíveis',
    'total-active': 'total ativo',
    'this-week': 'esta semana',
    'facilities': 'instalações',
    'active-plans': 'ativo',
    'last-7-days': 'Últimos 7 dias',
    'check-ins-this-week': 'check-ins esta semana',
    'students-actively-training': 'Alunos treinando ativamente',
    'classes-scheduled-today': 'aulas agendadas hoje',
    'active-class-schedule': 'Horário de aulas ativo',
    'active-training-plans': 'planos de treino ativos',
    'students-with-ongoing-programs': 'Alunos com programas em andamento',
    
    // Sidebar specific
    'teachers-instructors': 'Professores e Instrutores',
    'class-schedules': 'Horários de Aulas',
    'user-profiles': 'Perfis de Usuário',
    'company-info-settings': 'Informações e Configurações da Empresa',
    'language-settings': 'Configurações de Idioma',
    'app-settings': 'Configurações do App',
    
    // Student specific
    'preferred-language': 'Idioma Preferido para Interações',
    'preferred-language-help': 'Idioma usado para notificações do WhatsApp e comunicações do sistema'
  },
  GER: {
    // Main Menu Items
    'students': 'Schüler',
    'teachers': 'Lehrer',
    'championships': 'Meisterschaften',
    'classes': 'Klassen',
    'fight-plans': 'Kampfpläne',
    'fight-modalities': 'Kampfmodalitäten',
    'quality-evaluation': 'Qualität & Bewertung',
    'branches': 'Zweigstellen',
    'schedules-checkins': 'Zeitpläne & Check-ins',
    'administration': 'Administration',
    'dashboard': 'Dashboard',
    'management-system': 'Verwaltungssystem',
    'welcome-message': 'Willkommen zu Ihrem Jiu-Jitsu-Akademie-Verwaltungssystem - Moderne UI bereitgestellt!',
    'welcome-admin': 'Willkommen zurück, Admin',
    'total-students': 'Gesamte Schüler',
    'instructors': 'Ausbilder',
    'recent-activity': 'Letzte Aktivität',
    'quick-actions': 'Schnellaktionen',
    'add-new-student': 'Neuen Schüler hinzufügen',
    'add-new-instructor': 'Neuen Ausbilder hinzufügen',
    'add-martial-art-type': 'Kampfkunsttyp hinzufügen',
    'no-recent-activity': 'Keine letzte Aktivität',
    'start-adding': 'Beginnen Sie mit dem Hinzufügen von Schülern oder Ausbildern',
    'save-settings': 'Einstellungen speichern',
    'settings-saved': 'Einstellungen erfolgreich gespeichert!',
    
    // Dashboard specific
    'total-students': 'Gesamte Schüler',
    'instructors': 'Ausbilder',
    'fight-modalities': 'Kampfmodalitäten',
    'classes-today': 'Klassen Heute',
    'total-check-ins': 'Gesamte Check-ins',
    'branches': 'Zweigstellen',
    'training-plans': 'Trainingspläne',
    'recent-activity': 'Letzte Aktivität',
    'quick-actions': 'Schnellaktionen',
    'add-new-student': 'Neuen Schüler hinzufügen',
    'add-new-instructor': 'Neuen Ausbilder hinzufügen',
    'create-class-schedule': 'Klassenplan erstellen',
    'check-in-student': 'Schüler einchecken',
    'active': 'aktiv',
    'active-teachers': 'Aktive Lehrer',
    'available-styles': 'Verfügbare Stile',
    'total-active': 'gesamt aktiv',
    'this-week': 'diese Woche',
    'facilities': 'Einrichtungen',
    'active-plans': 'aktiv',
    'last-7-days': 'Letzte 7 Tage',
    'check-ins-this-week': 'Check-ins diese Woche',
    'students-actively-training': 'Schüler trainieren aktiv',
    'classes-scheduled-today': 'Klassen heute geplant',
    'active-class-schedule': 'Aktiver Klassenplan',
    'active-training-plans': 'aktive Trainingspläne',
    'students-with-ongoing-programs': 'Schüler mit laufenden Programmen',
    
    // Sidebar specific
    'teachers-instructors': 'Lehrer & Ausbilder',
    'class-schedules': 'Klassenpläne',
    'user-profiles': 'Benutzerprofile',
    'company-info-settings': 'Firmeninfo & Einstellungen',
    'language-settings': 'Spracheinstellungen',
    'app-settings': 'App-Einstellungen',
    
    // Student specific
    'preferred-language': 'Bevorzugte Sprache für Interaktionen',
    'preferred-language-help': 'Sprache für WhatsApp-Benachrichtigungen und Systemkommunikation'
  },
  FRA: {
    // Main Menu Items
    'students': 'Étudiants',
    'teachers': 'Professeurs',
    'championships': 'Championnats',
    'classes': 'Classes',
    'fight-plans': 'Plans de Combat',
    'fight-modalities': 'Modalités de Combat',
    'quality-evaluation': 'Qualité & Évaluation',
    'branches': 'Succursales',
    'schedules-checkins': 'Horaires & Enregistrements',
    'administration': 'Administration',
    'dashboard': 'Tableau de Bord',
    'management-system': 'Système de Gestion',
    'welcome-message': 'Bienvenue dans votre Système de Gestion d\'Académie de Jiu-Jitsu - Interface Moderne Déployée!',
    'welcome-admin': 'Bon retour, Admin',
    'total-students': 'Total des Étudiants',
    'instructors': 'Instructeurs',
    'recent-activity': 'Activité Récente',
    'quick-actions': 'Actions Rapides',
    'add-new-student': 'Ajouter un Nouvel Étudiant',
    'add-new-instructor': 'Ajouter un Nouvel Instructeur',
    'add-martial-art-type': 'Ajouter un Type d\'Art Martial',
    'no-recent-activity': 'Aucune activité récente',
    'start-adding': 'Commencez par ajouter des étudiants ou des instructeurs',
    'save-settings': 'Enregistrer les Paramètres',
    'settings-saved': 'Paramètres enregistrés avec succès!',
    
    // Dashboard specific
    'total-students': 'Total des Étudiants',
    'instructors': 'Instructeurs',
    'fight-modalities': 'Modalités de Combat',
    'classes-today': 'Classes Aujourd\'hui',
    'total-check-ins': 'Total des Enregistrements',
    'branches': 'Succursales',
    'training-plans': 'Plans d\'Entraînement',
    'recent-activity': 'Activité Récente',
    'quick-actions': 'Actions Rapides',
    'add-new-student': 'Ajouter un Nouvel Étudiant',
    'add-new-instructor': 'Ajouter un Nouvel Instructeur',
    'create-class-schedule': 'Créer un Planning de Classe',
    'check-in-student': 'Enregistrer un Étudiant',
    'active': 'actif',
    'active-teachers': 'Professeurs actifs',
    'available-styles': 'Styles disponibles',
    'total-active': 'total actif',
    'this-week': 'cette semaine',
    'facilities': 'installations',
    'active-plans': 'actif',
    'last-7-days': 'Derniers 7 jours',
    'check-ins-this-week': 'enregistrements cette semaine',
    'students-actively-training': 'Étudiants s\'entraînant activement',
    'classes-scheduled-today': 'classes programmées aujourd\'hui',
    'active-class-schedule': 'Planning de classe actif',
    'active-training-plans': 'plans d\'entraînement actifs',
    'students-with-ongoing-programs': 'Étudiants avec des programmes en cours',
    
    // Sidebar specific
    'teachers-instructors': 'Professeurs & Instructeurs',
    'class-schedules': 'Plannings de Classes',
    'user-profiles': 'Profils Utilisateur',
    'company-info-settings': 'Infos Entreprise & Paramètres',
    'language-settings': 'Paramètres de Langue',
    'app-settings': 'Paramètres de l\'App',
    
    // Student specific
    'preferred-language': 'Langue Préférée pour les Interactions',
    'preferred-language-help': 'Langue utilisée pour les notifications WhatsApp et communications système'
  },
  ESP: {
    // Main Menu Items
    'students': 'Estudiantes',
    'teachers': 'Profesores',
    'championships': 'Campeonatos',
    'classes': 'Clases',
    'fight-plans': 'Planes de Lucha',
    'fight-modalities': 'Modalidades de Lucha',
    'quality-evaluation': 'Calidad & Evaluación',
    'branches': 'Sucursales',
    'schedules-checkins': 'Horarios & Registros',
    'administration': 'Administración',
    'dashboard': 'Panel de Control',
    'management-system': 'Sistema de Gestión',
    'welcome-message': '¡Bienvenido a tu Sistema de Gestión de Academia de Jiu-Jitsu - Interfaz Moderna Desplegada!',
    'welcome-admin': 'Bienvenido de vuelta, Admin',
    'total-students': 'Total de Estudiantes',
    'instructors': 'Instructores',
    'recent-activity': 'Actividad Reciente',
    'quick-actions': 'Acciones Rápidas',
    'add-new-student': 'Agregar Nuevo Estudiante',
    'add-new-instructor': 'Agregar Nuevo Instructor',
    'add-martial-art-type': 'Agregar Tipo de Arte Marcial',
    'no-recent-activity': 'Sin actividad reciente',
    'start-adding': 'Comience agregando estudiantes o instructores',
    'save-settings': 'Guardar Configuración',
    'settings-saved': '¡Configuración guardada exitosamente!',
    
    // Dashboard specific
    'total-students': 'Total de Estudiantes',
    'instructors': 'Instructores',
    'fight-modalities': 'Modalidades de Lucha',
    'classes-today': 'Clases Hoy',
    'total-check-ins': 'Total de Registros',
    'branches': 'Sucursales',
    'training-plans': 'Planes de Entrenamiento',
    'recent-activity': 'Actividad Reciente',
    'quick-actions': 'Acciones Rápidas',
    'add-new-student': 'Agregar Nuevo Estudiante',
    'add-new-instructor': 'Agregar Nuevo Instructor',
    'create-class-schedule': 'Crear Horario de Clase',
    'check-in-student': 'Registrar Estudiante',
    'active': 'activo',
    'active-teachers': 'Profesores activos',
    'available-styles': 'Estilos disponibles',
    'total-active': 'total activo',
    'this-week': 'esta semana',
    'facilities': 'instalaciones',
    'active-plans': 'activo',
    'last-7-days': 'Últimos 7 días',
    'check-ins-this-week': 'registros esta semana',
    'students-actively-training': 'Estudiantes entrenando activamente',
    'classes-scheduled-today': 'clases programadas hoy',
    'active-class-schedule': 'Horario de clases activo',
    'active-training-plans': 'planes de entrenamiento activos',
    'students-with-ongoing-programs': 'Estudiantes con programas en curso',
    
    // Sidebar specific
    'teachers-instructors': 'Profesores e Instructores',
    'class-schedules': 'Horarios de Clases',
    'user-profiles': 'Perfiles de Usuario',
    'company-info-settings': 'Info de Empresa y Configuración',
    'language-settings': 'Configuración de Idioma',
    'app-settings': 'Configuración de la App',
    
    // Student specific
    'preferred-language': 'Idioma Preferido para Interacciones',
    'preferred-language-help': 'Idioma usado para notificaciones de WhatsApp y comunicaciones del sistema'
  },
  JPN: {
    // Main Menu Items
    'students': '学生',
    'teachers': '教師',
    'championships': '大会',
    'classes': 'クラス',
    'fight-plans': '戦闘計画',
    'fight-modalities': '格闘技モダリティ',
    'quality-evaluation': '品質・評価',
    'branches': '支店',
    'schedules-checkins': 'スケジュール・チェックイン',
    'administration': '管理',
    'dashboard': 'ダッシュボード',
    'management-system': '管理システム',
    'welcome-message': '柔術アカデミー管理システムへようこそ - モダンUI配信完了！',
    'welcome-admin': 'おかえりなさい、管理者',
    'total-students': '総学生数',
    'instructors': 'インストラクター',
    'recent-activity': '最近の活動',
    'quick-actions': 'クイックアクション',
    'add-new-student': '新しい学生を追加',
    'add-new-instructor': '新しいインストラクターを追加',
    'add-martial-art-type': '武道タイプを追加',
    'no-recent-activity': '最近の活動なし',
    'start-adding': '学生やインストラクターの追加を開始',
    'save-settings': '設定を保存',
    'settings-saved': '設定が正常に保存されました！',
    
    // Dashboard specific
    'total-students': '総学生数',
    'instructors': 'インストラクター',
    'fight-modalities': '格闘技モダリティ',
    'classes-today': '今日のクラス',
    'total-check-ins': '総チェックイン数',
    'branches': '支店',
    'training-plans': 'トレーニング計画',
    'recent-activity': '最近の活動',
    'quick-actions': 'クイックアクション',
    'add-new-student': '新しい学生を追加',
    'add-new-instructor': '新しいインストラクターを追加',
    'create-class-schedule': 'クラススケジュールを作成',
    'check-in-student': '学生をチェックイン',
    'active': 'アクティブ',
    'active-teachers': 'アクティブな教師',
    'available-styles': '利用可能なスタイル',
    'total-active': '総アクティブ',
    'this-week': '今週',
    'facilities': '施設',
    'active-plans': 'アクティブ',
    'last-7-days': '過去7日間',
    'check-ins-this-week': '今週のチェックイン',
    'students-actively-training': '積極的にトレーニングしている学生',
    'classes-scheduled-today': '今日予定されているクラス',
    'active-class-schedule': 'アクティブなクラススケジュール',
    'active-training-plans': 'アクティブなトレーニング計画',
    'students-with-ongoing-programs': '進行中のプログラムを持つ学生',
    
    // Sidebar specific
    'teachers-instructors': '教師・インストラクター',
    'class-schedules': 'クラススケジュール',
    'user-profiles': 'ユーザープロファイル',
    'company-info-settings': '会社情報・設定',
    'language-settings': '言語設定',
    'app-settings': 'アプリ設定',
    
    // Student specific
    'preferred-language': 'インタラクション用優先言語',
    'preferred-language-help': 'WhatsApp通知とシステム通信に使用される言語'
  },
  ITA: {
    // Main Menu Items
    'students': 'Studenti',
    'teachers': 'Insegnanti',
    'championships': 'Campionati',
    'classes': 'Classi',
    'fight-plans': 'Piani di Combattimento',
    'fight-modalities': 'Modalità di Combattimento',
    'quality-evaluation': 'Qualità & Valutazione',
    'branches': 'Filiali',
    'schedules-checkins': 'Orari & Registrazioni',
    'administration': 'Amministrazione',
    'dashboard': 'Dashboard',
    'management-system': 'Sistema di Gestione',
    'welcome-message': 'Benvenuto nel tuo Sistema di Gestione Accademia Jiu-Jitsu - UI Moderna Distribuita!',
    'welcome-admin': 'Bentornato, Admin',
    'total-students': 'Totale Studenti',
    'instructors': 'Istruttori',
    'recent-activity': 'Attività Recente',
    'quick-actions': 'Azioni Rapide',
    'add-new-student': 'Aggiungi Nuovo Studente',
    'add-new-instructor': 'Aggiungi Nuovo Istruttore',
    'add-martial-art-type': 'Aggiungi Tipo di Arte Marziale',
    'no-recent-activity': 'Nessuna attività recente',
    'start-adding': 'Inizia aggiungendo studenti o istruttori',
    'save-settings': 'Salva Impostazioni',
    'settings-saved': 'Impostazioni salvate con successo!',
    
    // Dashboard specific
    'total-students': 'Totale Studenti',
    'instructors': 'Istruttori',
    'fight-modalities': 'Modalità di Combattimento',
    'classes-today': 'Classi Oggi',
    'total-check-ins': 'Totale Registrazioni',
    'branches': 'Filiali',
    'training-plans': 'Piani di Allenamento',
    'recent-activity': 'Attività Recente',
    'quick-actions': 'Azioni Rapide',
    'add-new-student': 'Aggiungi Nuovo Studente',
    'add-new-instructor': 'Aggiungi Nuovo Istruttore',
    'create-class-schedule': 'Crea Orario delle Classi',
    'check-in-student': 'Registra Studente',
    'active': 'attivo',
    'active-teachers': 'Insegnanti attivi',
    'available-styles': 'Stili disponibili',
    'total-active': 'totale attivo',
    'this-week': 'questa settimana',
    'facilities': 'strutture',
    'active-plans': 'attivo',
    'last-7-days': 'Ultimi 7 giorni',
    'check-ins-this-week': 'registrazioni questa settimana',
    'students-actively-training': 'Studenti che si allenano attivamente',
    'classes-scheduled-today': 'classi programmate oggi',
    'active-class-schedule': 'Orario delle classi attivo',
    'active-training-plans': 'piani di allenamento attivi',
    'students-with-ongoing-programs': 'Studenti con programmi in corso',
    
    // Sidebar specific
    'teachers-instructors': 'Insegnanti & Istruttori',
    'class-schedules': 'Orari delle Classi',
    'user-profiles': 'Profili Utente',
    'company-info-settings': 'Info Azienda & Impostazioni',
    'language-settings': 'Impostazioni Lingua',
    'app-settings': 'Impostazioni App',
    
    // Student specific
    'preferred-language': 'Lingua Preferita per le Interazioni',
    'preferred-language-help': 'Lingua utilizzata per le notifiche WhatsApp e comunicazioni di sistema'
  },
  RUS: {
    // Main Menu Items
    'students': 'Студенты',
    'teachers': 'Преподаватели',
    'championships': 'Чемпионаты',
    'classes': 'Классы',
    'fight-plans': 'Планы Боев',
    'fight-modalities': 'Боевые Модальности',
    'quality-evaluation': 'Качество & Оценка',
    'branches': 'Филиалы',
    'schedules-checkins': 'Расписания & Регистрации',
    'administration': 'Администрация',
    'dashboard': 'Панель Управления',
    'management-system': 'Система Управления',
    'welcome-message': 'Добро пожаловать в вашу Систему Управления Академией Джиу-Джитсу - Современный UI Развернут!',
    'welcome-admin': 'Добро пожаловать обратно, Админ',
    'total-students': 'Всего Студентов',
    'instructors': 'Инструкторы',
    'recent-activity': 'Недавняя Активность',
    'quick-actions': 'Быстрые Действия',
    'add-new-student': 'Добавить Нового Студента',
    'add-new-instructor': 'Добавить Нового Инструктора',
    'add-martial-art-type': 'Добавить Тип Боевого Искусства',
    'no-recent-activity': 'Нет недавней активности',
    'start-adding': 'Начните с добавления студентов или инструкторов',
    'save-settings': 'Сохранить Настройки',
    'settings-saved': 'Настройки успешно сохранены!',
    
    // Dashboard specific
    'total-students': 'Всего Студентов',
    'instructors': 'Инструкторы',
    'fight-modalities': 'Боевые Модальности',
    'classes-today': 'Классы Сегодня',
    'total-check-ins': 'Всего Регистраций',
    'branches': 'Филиалы',
    'training-plans': 'Планы Тренировок',
    'recent-activity': 'Недавняя Активность',
    'quick-actions': 'Быстрые Действия',
    'add-new-student': 'Добавить Нового Студента',
    'add-new-instructor': 'Добавить Нового Инструктора',
    'create-class-schedule': 'Создать Расписание Классов',
    'check-in-student': 'Зарегистрировать Студента',
    'active': 'активный',
    'active-teachers': 'Активные преподаватели',
    'available-styles': 'Доступные стили',
    'total-active': 'всего активных',
    'this-week': 'на этой неделе',
    'facilities': 'объекты',
    'active-plans': 'активный',
    'last-7-days': 'Последние 7 дней',
    'check-ins-this-week': 'регистрации на этой неделе',
    'students-actively-training': 'Студенты активно тренируются',
    'classes-scheduled-today': 'классы запланированы на сегодня',
    'active-class-schedule': 'Активное расписание классов',
    'active-training-plans': 'активные планы тренировок',
    'students-with-ongoing-programs': 'Студенты с текущими программами',
    
    // Sidebar specific
    'teachers-instructors': 'Преподаватели & Инструкторы',
    'class-schedules': 'Расписания Классов',
    'user-profiles': 'Профили Пользователей',
    'company-info-settings': 'Информация о Компании & Настройки',
    'language-settings': 'Настройки Языка',
    'app-settings': 'Настройки Приложения',
    
    // Student specific
    'preferred-language': 'Предпочитаемый Язык для Взаимодействий',
    'preferred-language-help': 'Язык, используемый для уведомлений WhatsApp и системных сообщений'
  },
  ARA: {
    // Main Menu Items
    'students': 'الطلاب',
    'teachers': 'المعلمون',
    'championships': 'البطولات',
    'classes': 'الفصول',
    'fight-plans': 'خطط القتال',
    'fight-modalities': 'طرق القتال',
    'quality-evaluation': 'الجودة والتقييم',
    'branches': 'الفروع',
    'schedules-checkins': 'الجدول الزمني والتسجيل',
    'administration': 'الإدارة',
    'dashboard': 'لوحة التحكم',
    'management-system': 'نظام الإدارة',
    'welcome-message': 'مرحباً بك في نظام إدارة أكاديمية الجيو جيتسو - واجهة مستخدم حديثة تم نشرها!',
    'welcome-admin': 'مرحباً بعودتك، المدير',
    'total-students': 'إجمالي الطلاب',
    'instructors': 'المدربون',
    'recent-activity': 'النشاط الأخير',
    'quick-actions': 'الإجراءات السريعة',
    'add-new-student': 'إضافة طالب جديد',
    'add-new-instructor': 'إضافة مدرب جديد',
    'add-martial-art-type': 'إضافة نوع فن قتالي',
    'no-recent-activity': 'لا يوجد نشاط حديث',
    'start-adding': 'ابدأ بإضافة الطلاب أو المدربين',
    'save-settings': 'حفظ الإعدادات',
    'settings-saved': 'تم حفظ الإعدادات بنجاح!',
    
    // Dashboard specific
    'total-students': 'إجمالي الطلاب',
    'instructors': 'المدربون',
    'fight-modalities': 'طرق القتال',
    'classes-today': 'الفصول اليوم',
    'total-check-ins': 'إجمالي التسجيلات',
    'branches': 'الفروع',
    'training-plans': 'خطط التدريب',
    'recent-activity': 'النشاط الأخير',
    'quick-actions': 'الإجراءات السريعة',
    'add-new-student': 'إضافة طالب جديد',
    'add-new-instructor': 'إضافة مدرب جديد',
    'create-class-schedule': 'إنشاء جدول الفصول',
    'check-in-student': 'تسجيل الطالب',
    'active': 'نشط',
    'active-teachers': 'المعلمون النشطون',
    'available-styles': 'الأساليب المتاحة',
    'total-active': 'إجمالي النشط',
    'this-week': 'هذا الأسبوع',
    'facilities': 'المرافق',
    'active-plans': 'نشط',
    'last-7-days': 'آخر 7 أيام',
    'check-ins-this-week': 'تسجيلات هذا الأسبوع',
    'students-actively-training': 'الطلاب يتدربون بنشاط',
    'classes-scheduled-today': 'فصول مجدولة اليوم',
    'active-class-schedule': 'جدول الفصول النشط',
    'active-training-plans': 'خطط التدريب النشطة',
    'students-with-ongoing-programs': 'الطلاب مع البرامج الجارية',
    
    // Sidebar specific
    'teachers-instructors': 'المعلمون والمدربون',
    'class-schedules': 'جداول الفصول',
    'user-profiles': 'ملفات المستخدمين',
    'company-info-settings': 'معلومات الشركة والإعدادات',
    'language-settings': 'إعدادات اللغة',
    'app-settings': 'إعدادات التطبيق',
    
    // Student specific
    'preferred-language': 'اللغة المفضلة للتفاعلات',
    'preferred-language-help': 'اللغة المستخدمة لإشعارات الواتساب والاتصالات النظامية'
  },
  KOR: {
    // Main Menu Items
    'students': '학생',
    'teachers': '교사',
    'championships': '챔피언십',
    'classes': '수업',
    'fight-plans': '격투 계획',
    'fight-modalities': '격투 양식',
    'quality-evaluation': '품질 및 평가',
    'branches': '지점',
    'schedules-checkins': '일정 및 체크인',
    'administration': '관리',
    'dashboard': '대시보드',
    'management-system': '관리 시스템',
    'welcome-message': '주짓수 아카데미 관리 시스템에 오신 것을 환영합니다 - 현대적 UI 배포 완료!',
    'welcome-admin': '다시 오신 것을 환영합니다, 관리자',
    'total-students': '총 학생 수',
    'instructors': '강사',
    'recent-activity': '최근 활동',
    'quick-actions': '빠른 작업',
    'add-new-student': '새 학생 추가',
    'add-new-instructor': '새 강사 추가',
    'add-martial-art-type': '무술 유형 추가',
    'no-recent-activity': '최근 활동 없음',
    'start-adding': '학생이나 강사 추가를 시작하세요',
    'save-settings': '설정 저장',
    'settings-saved': '설정이 성공적으로 저장되었습니다!',
    
    // Dashboard specific
    'total-students': '총 학생 수',
    'instructors': '강사',
    'fight-modalities': '격투 양식',
    'classes-today': '오늘의 수업',
    'total-check-ins': '총 체크인 수',
    'branches': '지점',
    'training-plans': '훈련 계획',
    'recent-activity': '최근 활동',
    'quick-actions': '빠른 작업',
    'add-new-student': '새 학생 추가',
    'add-new-instructor': '새 강사 추가',
    'create-class-schedule': '수업 일정 생성',
    'check-in-student': '학생 체크인',
    'active': '활성',
    'active-teachers': '활성 교사',
    'available-styles': '사용 가능한 스타일',
    'total-active': '총 활성',
    'this-week': '이번 주',
    'facilities': '시설',
    'active-plans': '활성',
    'last-7-days': '지난 7일',
    'check-ins-this-week': '이번 주 체크인',
    'students-actively-training': '적극적으로 훈련하는 학생',
    'classes-scheduled-today': '오늘 예정된 수업',
    'active-class-schedule': '활성 수업 일정',
    'active-training-plans': '활성 훈련 계획',
    'students-with-ongoing-programs': '진행 중인 프로그램을 가진 학생',
    
    // Sidebar specific
    'teachers-instructors': '교사 및 강사',
    'class-schedules': '수업 일정',
    'user-profiles': '사용자 프로필',
    'company-info-settings': '회사 정보 및 설정',
    'language-settings': '언어 설정',
    'app-settings': '앱 설정',
    
    // Student specific
    'preferred-language': '상호작용을 위한 선호 언어',
    'preferred-language-help': 'WhatsApp 알림 및 시스템 통신에 사용되는 언어'
  }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('PTB')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('academy-language') as Language
    if (savedLanguage && ['ENU', 'PTB', 'ESP', 'FRA', 'GER', 'JPN', 'ITA', 'RUS', 'ARA', 'KOR'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('academy-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
