import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'ENU' | 'PTB' | 'GER' | 'FRA' | 'ESP' | 'JPN' | 'ITA' | 'RUS' | 'ARA' | 'KOR'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  ENU: {
    // Basic navigation
    'dashboard': 'Dashboard',
    'students': 'Students',
    'coach-students': 'Coach & Students',
    'teachers-instructors': 'Teachers & Instructors',
    'championships': 'Championships',
    'administration': 'Administration',
    
    // Dashboard specific translations
    'welcome-message': 'Welcome to your Fight Academy Manager',
    'total-students': 'Total Students',
    'active-teachers': 'Active Teachers',
    'fight-modalities': 'Fight Modalities',
    'available-styles': 'Available Styles',
    'classes-today': 'Classes Today',
    'total-active': 'Total Active',
    'total-check-ins': 'Total Check-ins',
    'this-week': 'This Week',
    'training-plans': 'Training Plans',
    'active-plans': 'Active Plans',
    'recent-activity': 'Recent Activity',
    'last-7-days': 'Last 7 Days',
    'check-ins-this-week': 'Check-ins This Week',
    'students-actively-training': 'Students Actively Training',
    'classes-scheduled-today': 'Classes Scheduled Today',
    'active-class-schedule': 'Active Class Schedule',
    'active-training-plans': 'Active Training Plans',
    'students-with-ongoing-programs': 'Students with Ongoing Programs',
    'quick-actions': 'Quick Actions',
    'add-new-student': 'Add New Student',
    'add-new-instructor': 'Add New Instructor',
    'create-class-schedule': 'Create Class Schedule',
    'check-in-student': 'Check-in Student',
    
    // Sidebar navigation
    'class-schedules': 'Class Schedules',
    'fight-plans': 'Fight Plans',
    'quality-evaluation': 'Quality Evaluation',
    'branches': 'Branches',
    
    // Students page translations
    'manage-student-activities': 'Manage Student Activities',
    'manage-coach-students-data': 'Manage Coach and Students Data',
    'company-info-settings': 'Company Info & Settings',
    'manage-company-info': 'Manage your academy\'s company information and system language',
    'company-fight-team': 'Company Fight Team',
    'select-company-fight-team': 'Select the fight team that represents your company',
    'company-fight-team-description': 'Choose which fight team your academy officially represents in competitions and events',
    'student-registration': 'Student Registration',
    'register-new-students': 'Register new students and manage student information',
    'modality-by-student': 'Fight Training Plan',
    'student-modality-management': 'Manage student modality assignments and training plans',
    'student-evaluation': 'Student Evaluation',
    'evaluate-student-progress': 'Evaluate student progress and performance',
    'student-attendance': 'Student Attendance',
    'track-student-attendance': 'Track student attendance and participation',
    
    // Teachers page translations
    'manage-teacher-activities': 'Manage Teacher Activities',
    'teacher-registration': 'Teacher Registration',
    'register-new-teachers': 'Register new teachers and manage teacher information',
    'coach-registration': 'Coach Registration',
    'register-new-coaches': 'Register new coaches and manage coach information',
    'teacher-profiles': 'Teacher Profiles',
    'view-manage-teacher-profiles': 'View and manage teacher profiles and information',
    'assign-teachers': 'Assign Teachers',
    'assign-teachers-to-classes-desc': 'Assign teachers to classes and manage teaching schedules',
    'teacher-evaluations': 'Teacher Evaluations',
    'evaluate-teacher-performance': 'Evaluate teacher performance and provide feedback',
    
    // Fight Plans page translations
    'modality-management': 'Manage fight modalities and styles',
    'training-phases': 'Training Phases',
    
    // Branches page translations
    'branch-registration': 'Branch Registration',
    'branch-facilities': 'Branch Facilities',
    
    // Fight Teams translations
    'fight-teams': 'Fight Teams',
    'manage-fight-teams': 'Manage Fight Teams',
    'new-fight-team': 'New Fight Team',
    'edit-fight-team': 'Edit Fight Team',
    'view-fight-team': 'View Fight Team',
    'edit-fight-team-description': 'Edit fight team details and information',
    'view-fight-team-description': 'View fight team information and details',
    'new-fight-team-description': 'Create a new fight team',
    'back-to-teams': 'Back to Teams',
    'team-id': 'Team ID',
    'team-name': 'Team Name',
    'team-name-placeholder': 'Enter team name',
    'coach': 'Coach',
    'select-coach': 'Select Coach',
    'select-branch': 'Select Branch',
    'established-date': 'Established Date',
    'country-code': 'Country Code',
    'country-code-placeholder': 'Enter country code (e.g., BR, US, AE)',
    'fight-modalities-description': 'Select the fight modalities that this team presents (can be multiple)',
    'max-team-size': 'Max Team Size',
    'max-team-size-placeholder': 'Enter maximum team size',
    'team-description-placeholder': 'Enter team description',
    'team-logo': 'Team Logo',
    'click-to-upload': 'Click to upload',
    'or-drag-and-drop': 'or drag and drop',
    'logo-upload-formats': 'PNG, JPG, GIF up to 2MB',
    'logo-preview': 'Logo Preview',
    'team-logo-alt': 'Team Logo',
    'logo': 'Logo',
    'file-too-large': 'File is too large. Please select an image smaller than 2MB.',
    'invalid-file-type': 'Invalid file type. Please select an image file.',
    
    // Championship Category Form
    'view-category': 'View Category',
    'new-category-description': 'Create a new championship category',
    'edit-category-description': 'Edit championship category details',
    'view-category-description': 'View championship category information',
    'select-championship': 'Select Championship',
    'weight-category-placeholder': 'Enter weight category (e.g., Lightweight, Middleweight)',
    'category-description-placeholder': 'Enter category description and rules',
    'update-category': 'Update Category',
    'create-category': 'Create Category',
    'error-saving-category': 'Error saving category. Please try again.',
    'team-members': 'Team Members',
    'select-student': 'Select Student',
    'achievements': 'Achievements',
    'achievement-placeholder': 'Enter achievement',
    'contact-information': 'Contact Information',
    'contact-email-placeholder': 'Enter contact email',
    'contact-phone-placeholder': 'Enter contact phone',
    'notes-placeholder': 'Enter additional notes',
    'active-team': 'Active Team',
    'update-team': 'Update Team',
    'create-team': 'Create Team',
    'search-teams': 'Search teams...',
    'all-branches': 'All Branches',
    'all-modalities': 'All Modalities',
    'all-status': 'All Status',
    'team-size': 'Team Size',
    'established': 'Established',
    'no-teams-found': 'No Teams Found',
    'no-teams-found-description': 'No fight teams match your current filters',
    'create-first-team': 'Create First Team',
    'confirm-delete-team': 'Are you sure you want to delete this fight team?',
    'fill-required-fields': 'Please fill in all required fields',
    'remove': 'Remove',
    
    // Common actions
    'new': 'New',
    'edit': 'Edit',
    'view': 'View',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'back': 'Back',
    'search': 'Search',
    'filter': 'Filter',
    'export': 'Export',
    'import': 'Import',
    'loading': 'Loading...',
    'no-data': 'No data found',
    'confirm-delete': 'Are you sure you want to delete this item?',
    
    // Championship module
    'championship-registration': 'Championship Registration',
    'student-enrollment': 'Student Enrollment in Championships',
    'championship-results': 'Championship Results',
    'ranking-statistics': 'Ranking & Statistics',
    'fight-associations': 'Fight Associations',
    'affiliations': 'Affiliations',
    'championship-categories': 'Championship Categories',
    'registrations': 'Registrations',
    'referees-officials': 'Referees / Officials',
    'championship-sponsors': 'Championship Sponsors',
    'championship-qualified-locations': 'Championship Qualified Locations',
    
    // Championship specific translations
    'manage-championship-registrations': 'Manage Championship Registrations',
    'search-championships': 'Search championships...',
    'association': 'Association',
    'all-associations': 'All Associations',
    'actions': 'Actions',
    'no-championships-found': 'No Championships Found',
    'no-championships-found-description': 'No championships match your current filters. Try adjusting your search criteria or create a new championship.',
    'create-first-championship': 'Create First Championship',
    'confirm-delete-championship': 'Are you sure you want to delete this championship?',
    
    // Championship forms
    'championship-id': 'Championship ID',
    'association-id': 'Association ID',
    'championship-name': 'Championship Name',
    'championship-location': 'Location',
    'start-date': 'Start Date',
    'end-date': 'End Date',
    'registration-deadline': 'Registration Deadline',
    'fight-modality': 'Fight Modality',
    'status': 'Status',
    'upcoming': 'Upcoming',
    'ongoing': 'Ongoing',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'new-championship': 'New Championship',
    'edit-championship': 'Edit Championship',
    'edit-championship-description': 'Edit championship details and information',
    'new-championship-description': 'Create a new championship registration',
    'back-to-championships': 'Back to Championships',
    'save-championship': 'Save Championship',
    'select-association': 'Select Association',
    'championship-name-placeholder': 'Enter championship name',
    'championship-location-placeholder': 'Enter championship location',
    'select-modality': 'Select Modality',
    'additional-information': 'Additional Information',
    'max-participants': 'Max Participants',
    'max-participants-placeholder': 'Enter maximum participants',
    'entry-fee': 'Entry Fee',
    'entry-fee-placeholder': 'Enter entry fee amount',
    'organizer': 'Organizer',
    'organizer-placeholder': 'Enter organizer name',
    'contact-email': 'Contact Email',
    'contact-phone': 'Contact Phone',
    'championship-description': 'Championship Description',
    'championship-description-placeholder': 'Enter championship description',
    'select-qualified-location': 'Select Qualified Location',
    
    // Qualified Locations specific translations
    'manage-qualified-locations': 'Manage Championship Qualified Locations',
    'new-qualified-location': 'New Qualified Location',
    'edit-qualified-location': 'Edit Qualified Location',
    'edit-location-description': 'Edit qualified location details and information',
    'new-location-description': 'Create a new qualified location for championships',
    'back-to-locations': 'Back to Qualified Locations',
    'save-location': 'Save Location',
    'search-locations': 'Search locations...',
    'location-id': 'Location ID',
    'location-name': 'Location Name',
    'location-name-placeholder': 'Enter location name',
    'address-placeholder': 'Enter full address',
    'city-placeholder': 'Enter city name',
    'state-placeholder': 'Enter state/province',
    'country-placeholder': 'Enter country name',
    'postal-code': 'Postal Code',
    'postal-code-placeholder': 'Enter postal/zip code',
    'capacity': 'Capacity',
    'capacity-placeholder': 'Enter maximum capacity',
    'facilities': 'Facilities',
    'add-facility-placeholder': 'Add facility (e.g., Main Arena, Parking)',
    'add': 'Add',
    'contact-person': 'Contact Person',
    'contact-person-placeholder': 'Enter contact person name',
    'certification-information': 'Certification Information',
    'certification-level': 'Certification Level',
    'certification-date': 'Certification Date',
    'certification-expiry': 'Certification Expiry',
    'basic': 'Basic',
    'intermediate': 'Intermediate',
    'advanced': 'Advanced',
    'premium': 'Premium',
    'all-levels': 'All Levels',
    'all-countries': 'All Countries',
    'no-locations-found': 'No Qualified Locations Found',
    'no-locations-found-description': 'No qualified locations match your current filters. Try adjusting your search criteria or create a new qualified location.',
    'create-first-location': 'Create First Qualified Location',
    'confirm-delete-location': 'Are you sure you want to delete this qualified location?',
    'location-image': 'Location Image',
    'image-url-placeholder': 'Enter image URL (e.g., https://example.com/image.jpg)',
    'image-preview': 'Image Preview',
    'location-image-alt': 'Location image',
    'image': 'Image',
    
    // Affiliation forms
    'affiliation-id': 'Affiliation ID',
    'student-id': 'Student ID',
    'membership-number': 'Membership Number',
    'affiliation-date': 'Affiliation Date',
    'notes': 'Notes',
    'new-affiliation': 'New Affiliation',
    'edit-affiliation': 'Edit Affiliation',
    'save-affiliation': 'Save Affiliation',
    
    // Category forms
    'category-id': 'Category ID',
    'age-group': 'Age Group',
    'weight-category': 'Weight Category',
    'gender': 'Gender',
    'mixed': 'Mixed',
    'all-belts': 'All Belts',
    'new-category': 'New Category',
    'edit-category': 'Edit Category',
    'save-category': 'Save Category',
    
    // Registration forms
    'registration-id': 'Registration ID',
    'teacher-id': 'Teacher ID',
    'registration-date': 'Registration Date',
    'weight': 'Weight',
    'payment-status': 'Payment Status',
    'medical-certificate': 'Medical Certificate',
    'insurance-number': 'Insurance Number',
    'paid': 'Paid',
    'pending': 'Pending',
    'refunded': 'Refunded',
    'new-registration': 'New Registration',
    'edit-registration': 'Edit Registration',
    'save-registration': 'Save Registration',
    
    // Result forms
    'result-id': 'Result ID',
    'position': 'Position',
    'points': 'Points',
    'medal-type': 'Medal Type',
    'gold': 'Gold',
    'silver': 'Silver',
    'bronze': 'Bronze',
    'none': 'None',
    '1st': '1st',
    '2nd': '2nd',
    '3rd': '3rd',
    'new-result': 'New Result',
    'edit-result': 'Edit Result',
    'save-result': 'Save Result',
    
    // Official forms
    'official-id': 'Official ID',
    'official-name': 'Official Name',
    'official-level': 'Official Level',
    'assigned-categories': 'Assigned Categories',
    'certification-number': 'Certification Number',
    'national': 'National',
    'international': 'International',
    'regional': 'Regional',
    'local': 'Local',
    'new-official': 'New Official',
    'edit-official': 'Edit Official',
    'save-official': 'Save Official',
    
    // Sponsor forms
    'sponsor-id': 'Sponsor ID',
    'sponsor-name': 'Sponsor Name',
    'sponsor-logo': 'Sponsor Logo',
    'sponsor-link': 'Sponsor Link',
    'sponsor-description': 'Sponsor Description',
    'sponsor-type': 'Sponsor Type',
    'contribution-amount': 'Contribution Amount',
    'title': 'Title',
    'supporting': 'Supporting',
    'new-sponsor': 'New Sponsor',
    'edit-sponsor': 'Edit Sponsor',
    'save-sponsor': 'Save Sponsor',
    
    // Common fields
    'name': 'Name',
    'description': 'Description',
    'date': 'Date',
    'time': 'Time',
    'location': 'Location',
    'contact': 'Contact',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'active': 'Active',
    'inactive': 'Inactive',
    'all': 'All',
    'select': 'Select',
    'required': 'Required',
    'optional': 'Optional',
    
    // Belt levels
    'white-belt': 'White Belt',
    'blue-belt': 'Blue Belt',
    'purple-belt': 'Purple Belt',
    'brown-belt': 'Brown Belt',
    'black-belt': 'Black Belt',
    
    // Age groups
    'adult': 'Adult',
    'kids': 'Kids',
    'master': 'Master',
    'senior': 'Senior',
    
    // Genders
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'unisex': 'Unisex',
    'womens-only': 'Women\'s Only'
  },
  
  PTB: {
    // Basic navigation
    'dashboard': 'Painel de Controle',
    'students': 'Estudantes',
    'coach-students': 'Técnicos e Estudantes',
    'teachers-instructors': 'Professores e Instrutores',
    'championships': 'Campeonatos',
    'administration': 'Administração',
    
    // Dashboard specific translations
    'welcome-message': 'Bem-vindo ao seu Gerenciador de Academia de Lutas',
    'total-students': 'Total de Estudantes',
    'active-teachers': 'Professores Ativos',
    'fight-modalities': 'Modalidades de Luta',
    'available-styles': 'Estilos Disponíveis',
    'classes-today': 'Aulas Hoje',
    'total-active': 'Total Ativo',
    'total-check-ins': 'Total de Check-ins',
    'this-week': 'Esta Semana',
    'training-plans': 'Planos de Treinamento',
    'active-plans': 'Planos Ativos',
    'recent-activity': 'Atividade Recente',
    'last-7-days': 'Últimos 7 Dias',
    'check-ins-this-week': 'Check-ins Esta Semana',
    'students-actively-training': 'Estudantes Treinando Ativamente',
    'classes-scheduled-today': 'Aulas Agendadas Hoje',
    'active-class-schedule': 'Cronograma de Aulas Ativo',
    'active-training-plans': 'Planos de Treinamento Ativos',
    'students-with-ongoing-programs': 'Estudantes com Programas em Andamento',
    'quick-actions': 'Ações Rápidas',
    'add-new-student': 'Adicionar Novo Estudante',
    'add-new-instructor': 'Adicionar Novo Instrutor',
    'create-class-schedule': 'Criar Cronograma de Aulas',
    'check-in-student': 'Check-in do Estudante',
    
    // Sidebar navigation
    'class-schedules': 'Cronogramas de Aulas',
    'fight-plans': 'Planos de Luta',
    'quality-evaluation': 'Avaliação de Qualidade',
    'branches': 'Filiais',
    
    // Students page translations
    'manage-student-activities': 'Gerenciar Atividades dos Estudantes',
    'manage-coach-students-data': 'Gerenciar Dados de Técnicos e Estudantes',
    'company-info-settings': 'Informações e Configurações da Empresa',
    'manage-company-info': 'Gerencie as informações da empresa da sua academia e idioma do sistema',
    'company-fight-team': 'Equipe de Luta da Empresa',
    'select-company-fight-team': 'Selecione a equipe de luta que representa sua empresa',
    'company-fight-team-description': 'Escolha qual equipe de luta sua academia representa oficialmente em competições e eventos',
    'student-registration': 'Registro de Estudantes',
    'register-new-students': 'Registrar novos estudantes e gerenciar informações dos estudantes',
    'modality-by-student': 'Plano de Treinamento de Luta',
    'student-modality-management': 'Gerenciar atribuições de modalidade e planos de treinamento dos estudantes',
    'student-evaluation': 'Avaliação de Estudantes',
    'evaluate-student-progress': 'Avaliar progresso e desempenho dos estudantes',
    'student-attendance': 'Frequência dos Estudantes',
    'track-student-attendance': 'Acompanhar frequência e participação dos estudantes',
    
    // Teachers page translations
    'manage-teacher-activities': 'Gerenciar Atividades dos Professores',
    'teacher-registration': 'Registro de Professores',
    'register-new-teachers': 'Registrar novos professores e gerenciar informações dos professores',
    'coach-registration': 'Registro de Treinadores',
    'register-new-coaches': 'Registrar novos treinadores e gerenciar informações dos treinadores',
    'teacher-profiles': 'Perfis dos Professores',
    'view-manage-teacher-profiles': 'Visualizar e gerenciar perfis e informações dos professores',
    'assign-teachers': 'Atribuir Professores',
    'assign-teachers-to-classes-desc': 'Atribuir professores às aulas e gerenciar cronogramas de ensino',
    'teacher-evaluations': 'Avaliações dos Professores',
    'evaluate-teacher-performance': 'Avaliar desempenho dos professores e fornecer feedback',
    
    // Fight Plans page translations
    'modality-management': 'Gerenciar modalidades e estilos de luta',
    'training-phases': 'Fases de Treinamento',
    
    // Branches page translations
    'branch-registration': 'Registro de Filiais',
    'branch-facilities': 'Instalações das Filiais',
    
    // Fight Teams translations
    'fight-teams': 'Equipes de Luta',
    'manage-fight-teams': 'Gerenciar Equipes de Luta',
    'new-fight-team': 'Nova Equipe de Luta',
    'edit-fight-team': 'Editar Equipe de Luta',
    'view-fight-team': 'Visualizar Equipe de Luta',
    'edit-fight-team-description': 'Editar detalhes e informações da equipe de luta',
    'view-fight-team-description': 'Visualizar informações e detalhes da equipe de luta',
    'new-fight-team-description': 'Criar uma nova equipe de luta',
    'back-to-teams': 'Voltar às Equipes',
    'team-id': 'ID da Equipe',
    'team-name': 'Nome da Equipe',
    'team-name-placeholder': 'Digite o nome da equipe',
    'coach': 'Técnico',
    'select-coach': 'Selecionar Técnico',
    'select-branch': 'Selecionar Filial',
    'established-date': 'Data de Fundação',
    'country-code': 'Código do País',
    'country-code-placeholder': 'Digite o código do país (ex: BR, US, AE)',
    'fight-modalities-description': 'Selecione as modalidades de luta que esta equipe apresenta (pode ser múltiplas)',
    'max-team-size': 'Tamanho Máximo da Equipe',
    'max-team-size-placeholder': 'Digite o tamanho máximo da equipe',
    'team-description-placeholder': 'Digite a descrição da equipe',
    'team-logo': 'Logo da Equipe',
    'click-to-upload': 'Clique para enviar',
    'or-drag-and-drop': 'ou arraste e solte',
    'logo-upload-formats': 'PNG, JPG, GIF até 2MB',
    'logo-preview': 'Visualização do Logo',
    'team-logo-alt': 'Logo da Equipe',
    'logo': 'Logo',
    'file-too-large': 'Arquivo muito grande. Selecione uma imagem menor que 2MB.',
    'invalid-file-type': 'Tipo de arquivo inválido. Selecione um arquivo de imagem.',
    
    // Championship Category Form
    'view-category': 'Ver Categoria',
    'new-category-description': 'Criar uma nova categoria de campeonato',
    'edit-category-description': 'Editar detalhes da categoria de campeonato',
    'view-category-description': 'Ver informações da categoria de campeonato',
    'select-championship': 'Selecionar Campeonato',
    'weight-category-placeholder': 'Digite a categoria de peso (ex: Leve, Médio)',
    'category-description-placeholder': 'Digite a descrição e regras da categoria',
    'update-category': 'Atualizar Categoria',
    'create-category': 'Criar Categoria',
    'error-saving-category': 'Erro ao salvar categoria. Tente novamente.',
    'team-members': 'Membros da Equipe',
    'select-student': 'Selecionar Estudante',
    'achievements': 'Conquistas',
    'achievement-placeholder': 'Digite a conquista',
    'contact-information': 'Informações de Contato',
    'contact-email-placeholder': 'Digite o email de contato',
    'contact-phone-placeholder': 'Digite o telefone de contato',
    'notes-placeholder': 'Digite observações adicionais',
    'active-team': 'Equipe Ativa',
    'update-team': 'Atualizar Equipe',
    'create-team': 'Criar Equipe',
    'search-teams': 'Pesquisar equipes...',
    'all-branches': 'Todas as Filiais',
    'all-modalities': 'Todas as Modalidades',
    'all-status': 'Todos os Status',
    'team-size': 'Tamanho da Equipe',
    'established': 'Fundada',
    'no-teams-found': 'Nenhuma Equipe Encontrada',
    'no-teams-found-description': 'Nenhuma equipe de luta corresponde aos filtros atuais',
    'create-first-team': 'Criar Primeira Equipe',
    'confirm-delete-team': 'Tem certeza de que deseja excluir esta equipe de luta?',
    'fill-required-fields': 'Por favor, preencha todos os campos obrigatórios',
    'remove': 'Remover',
    
    // Common actions
    'new': 'Novo',
    'edit': 'Editar',
    'view': 'Visualizar',
    'delete': 'Excluir',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'back': 'Voltar',
    'search': 'Pesquisar',
    'filter': 'Filtrar',
    'export': 'Exportar',
    'import': 'Importar',
    'loading': 'Carregando...',
    'no-data': 'Nenhum dado encontrado',
    'confirm-delete': 'Tem certeza de que deseja excluir este item?',
    
    // Championship module
    'championship-registration': 'Registro de Campeonato',
    'student-enrollment': 'Inscrição de Estudantes em Campeonatos',
    'championship-results': 'Resultados de Campeonato',
    'ranking-statistics': 'Ranking e Estatísticas',
    'fight-associations': 'Associações de Luta',
    'affiliations': 'Afiliações',
    'championship-categories': 'Categorias de Campeonato',
    'registrations': 'Inscrições',
    'referees-officials': 'Árbitros / Oficiais',
    'championship-sponsors': 'Patrocinadores de Campeonato',
    'championship-qualified-locations': 'Locais Qualificados para Campeonatos',
    
    // Championship specific translations
    'manage-championship-registrations': 'Gerenciar Registros de Campeonato',
    'search-championships': 'Pesquisar campeonatos...',
    'all-statuses': 'Todos os Status',
    'association': 'Associação',
    'all-associations': 'Todas as Associações',
    'actions': 'Ações',
    'no-championships-found': 'Nenhum Campeonato Encontrado',
    'no-championships-found-description': 'Nenhum campeonato corresponde aos seus filtros atuais. Tente ajustar seus critérios de pesquisa ou criar um novo campeonato.',
    'create-first-championship': 'Criar Primeiro Campeonato',
    'confirm-delete-championship': 'Tem certeza de que deseja excluir este campeonato?',
    
    // Championship forms
    'championship-id': 'ID do Campeonato',
    'association-id': 'ID da Associação',
    'championship-name': 'Nome do Campeonato',
    'championship-location': 'Local',
    'start-date': 'Data de Início',
    'end-date': 'Data de Término',
    'registration-deadline': 'Prazo de Inscrição',
    'fight-modality': 'Modalidade de Luta',
    'status': 'Status',
    'upcoming': 'Próximo',
    'ongoing': 'Em Andamento',
    'completed': 'Concluído',
    'cancelled': 'Cancelado',
    'new-championship': 'Novo Campeonato',
    'edit-championship': 'Editar Campeonato',
    'edit-championship-description': 'Editar detalhes e informações do campeonato',
    'new-championship-description': 'Criar um novo registro de campeonato',
    'back-to-championships': 'Voltar aos Campeonatos',
    'save-championship': 'Salvar Campeonato',
    'select-association': 'Selecionar Associação',
    'championship-name-placeholder': 'Digite o nome do campeonato',
    'championship-location-placeholder': 'Digite o local do campeonato',
    'select-modality': 'Selecionar Modalidade',
    'additional-information': 'Informações Adicionais',
    'max-participants': 'Máximo de Participantes',
    'max-participants-placeholder': 'Digite o máximo de participantes',
    'entry-fee': 'Taxa de Inscrição',
    'entry-fee-placeholder': 'Digite o valor da taxa de inscrição',
    'organizer': 'Organizador',
    'organizer-placeholder': 'Digite o nome do organizador',
    'contact-email': 'Email de Contato',
    'contact-phone': 'Telefone de Contato',
    'championship-description': 'Descrição do Campeonato',
    'championship-description-placeholder': 'Digite a descrição do campeonato',
    'select-qualified-location': 'Selecionar Local Qualificado',
    
    // Qualified Locations specific translations
    'manage-qualified-locations': 'Gerenciar Locais Qualificados para Campeonatos',
    'new-qualified-location': 'Novo Local Qualificado',
    'edit-qualified-location': 'Editar Local Qualificado',
    'edit-location-description': 'Editar detalhes e informações do local qualificado',
    'new-location-description': 'Criar um novo local qualificado para campeonatos',
    'back-to-locations': 'Voltar aos Locais Qualificados',
    'save-location': 'Salvar Local',
    'search-locations': 'Pesquisar locais...',
    'location-id': 'ID do Local',
    'location-name': 'Nome do Local',
    'location-name-placeholder': 'Digite o nome do local',
    'address-placeholder': 'Digite o endereço completo',
    'city-placeholder': 'Digite o nome da cidade',
    'state-placeholder': 'Digite o estado/província',
    'country-placeholder': 'Digite o nome do país',
    'postal-code': 'Código Postal',
    'postal-code-placeholder': 'Digite o código postal/CEP',
    'capacity': 'Capacidade',
    'capacity-placeholder': 'Digite a capacidade máxima',
    'facilities': 'Instalações',
    'add-facility-placeholder': 'Adicionar instalação (ex: Arena Principal, Estacionamento)',
    'add': 'Adicionar',
    'contact-person': 'Pessoa de Contato',
    'contact-person-placeholder': 'Digite o nome da pessoa de contato',
    'certification-information': 'Informações de Certificação',
    'certification-level': 'Nível de Certificação',
    'certification-date': 'Data de Certificação',
    'basic': 'Básico',
    'intermediate': 'Intermediário',
    'advanced': 'Avançado',
    'premium': 'Premium',
    'all-levels': 'Todos os Níveis',
    'all-countries': 'Todos os Países',
    'no-locations-found': 'Nenhum Local Qualificado Encontrado',
    'no-locations-found-description': 'Nenhum local qualificado corresponde aos seus filtros atuais. Tente ajustar seus critérios de pesquisa ou criar um novo local qualificado.',
    'create-first-location': 'Criar Primeiro Local Qualificado',
    'confirm-delete-location': 'Tem certeza de que deseja excluir este local qualificado?',
    'location-image': 'Imagem do Local',
    'image-url-placeholder': 'Digite a URL da imagem (ex: https://exemplo.com/imagem.jpg)',
    'image-preview': 'Visualização da Imagem',
    'location-image-alt': 'Imagem do local',
    'image': 'Imagem',
    
    // Affiliation forms
    'affiliation-id': 'ID da Afiliação',
    'student-id': 'ID do Estudante',
    'membership-number': 'Número de Membro',
    'affiliation-date': 'Data de Afiliação',
    'notes': 'Observações',
    'new-affiliation': 'Nova Afiliação',
    'edit-affiliation': 'Editar Afiliação',
    'save-affiliation': 'Salvar Afiliação',
    
    // Category forms
    'category-id': 'ID da Categoria',
    'age-group': 'Grupo Etário',
    'weight-category': 'Categoria de Peso',
    'gender': 'Gênero',
    'mixed': 'Misto',
    'all-belts': 'Todas as Faixas',
    'new-category': 'Nova Categoria',
    'edit-category': 'Editar Categoria',
    'save-category': 'Salvar Categoria',
    
    // Registration forms
    'registration-id': 'ID da Inscrição',
    'teacher-id': 'ID do Professor',
    'registration-date': 'Data de Inscrição',
    'weight': 'Peso',
    'payment-status': 'Status do Pagamento',
    'medical-certificate': 'Atestado Médico',
    'insurance-number': 'Número do Seguro',
    'paid': 'Pago',
    'pending': 'Pendente',
    'refunded': 'Reembolsado',
    'new-registration': 'Nova Inscrição',
    'edit-registration': 'Editar Inscrição',
    'save-registration': 'Salvar Inscrição',
    
    // Result forms
    'result-id': 'ID do Resultado',
    'position': 'Posição',
    'points': 'Pontos',
    'medal-type': 'Tipo de Medalha',
    'gold': 'Ouro',
    'silver': 'Prata',
    'bronze': 'Bronze',
    'none': 'Nenhuma',
    '1st': '1º',
    '2nd': '2º',
    '3rd': '3º',
    'new-result': 'Novo Resultado',
    'edit-result': 'Editar Resultado',
    'save-result': 'Salvar Resultado',
    
    // Official forms
    'official-id': 'ID do Oficial',
    'official-name': 'Nome do Oficial',
    'official-level': 'Nível do Oficial',
    'assigned-categories': 'Categorias Atribuídas',
    'certification-number': 'Número da Certificação',
    'certification-expiry': 'Expiração da Certificação',
    'national': 'Nacional',
    'international': 'Internacional',
    'regional': 'Regional',
    'local': 'Local',
    'new-official': 'Novo Oficial',
    'edit-official': 'Editar Oficial',
    'save-official': 'Salvar Oficial',
    
    // Sponsor forms
    'sponsor-id': 'ID do Patrocinador',
    'sponsor-name': 'Nome do Patrocinador',
    'sponsor-logo': 'Logo do Patrocinador',
    'sponsor-link': 'Link do Patrocinador',
    'sponsor-description': 'Descrição do Patrocinador',
    'sponsor-type': 'Tipo de Patrocinador',
    'contribution-amount': 'Valor da Contribuição',
    'title': 'Título',
    'supporting': 'Apoiador',
    'new-sponsor': 'Novo Patrocinador',
    'edit-sponsor': 'Editar Patrocinador',
    'save-sponsor': 'Salvar Patrocinador',
    
    // Common fields
    'name': 'Nome',
    'description': 'Descrição',
    'date': 'Data',
    'time': 'Hora',
    'location': 'Local',
    'contact': 'Contato',
    'email': 'Email',
    'phone': 'Telefone',
    'address': 'Endereço',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'all': 'Todos',
    'select': 'Selecionar',
    'required': 'Obrigatório',
    'optional': 'Opcional',
    
    // Belt levels
    'white-belt': 'Faixa Branca',
    'blue-belt': 'Faixa Azul',
    'purple-belt': 'Faixa Roxa',
    'brown-belt': 'Faixa Marrom',
    'black-belt': 'Faixa Preta',
    
    // Age groups
    'adult': 'Adulto',
    'kids': 'Crianças',
    'master': 'Master',
    'senior': 'Sênior',
    
    // Genders
    'male': 'Masculino',
    'female': 'Feminino',
    'other': 'Outro',
    'unisex': 'Unissex',
    'womens-only': 'Apenas Mulheres'
  },
  
  GER: {
    // Basic navigation
    'dashboard': 'Dashboard',
    'students': 'Schüler',
    'teachers-instructors': 'Lehrer & Ausbilder',
    'championships': 'Meisterschaften',
    'administration': 'Verwaltung',
    
    // Common actions
    'new': 'Neu',
    'edit': 'Bearbeiten',
    'view': 'Anzeigen',
    'delete': 'Löschen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'back': 'Zurück',
    'search': 'Suchen',
    'filter': 'Filtern',
    'export': 'Exportieren',
    'import': 'Importieren',
    'loading': 'Laden...',
    'no-data': 'Keine Daten gefunden',
    'confirm-delete': 'Sind Sie sicher, dass Sie dieses Element löschen möchten?',
    
    // Championship module
    'championship-registration': 'Meisterschaftsregistrierung',
    'student-enrollment': 'Schüleranmeldung zu Meisterschaften',
    'championship-results': 'Meisterschaftsergebnisse',
    'ranking-statistics': 'Ranking & Statistiken',
    'fight-associations': 'Kampfverbände',
    'affiliations': 'Zugehörigkeiten',
    'championship-categories': 'Meisterschaftskategorien',
    'registrations': 'Anmeldungen',
    'referees-officials': 'Schiedsrichter / Offizielle',
    'championship-sponsors': 'Meisterschaftssponsoren',
    
    // Common fields
    'name': 'Name',
    'description': 'Beschreibung',
    'date': 'Datum',
    'time': 'Zeit',
    'location': 'Ort',
    'contact': 'Kontakt',
    'email': 'E-Mail',
    'phone': 'Telefon',
    'address': 'Adresse',
    'active': 'Aktiv',
    'inactive': 'Inaktiv',
    'all': 'Alle',
    'select': 'Auswählen',
    'required': 'Erforderlich',
    'optional': 'Optional',
    
    // Belt levels
    'white-belt': 'Weißer Gürtel',
    'blue-belt': 'Blauer Gürtel',
    'purple-belt': 'Lila Gürtel',
    'brown-belt': 'Brauner Gürtel',
    'black-belt': 'Schwarzer Gürtel',
    
    // Age groups
    'adult': 'Erwachsene',
    'kids': 'Kinder',
    'master': 'Master',
    'senior': 'Senior',
    
    // Genders
    'male': 'Männlich',
    'female': 'Weiblich',
    'other': 'Andere',
    'unisex': 'Unisex',
    'womens-only': 'Nur Frauen',
    
    // Teachers page translations
    'teacher-registration': 'Lehrer-Registrierung',
    'register-new-teachers': 'Neue Lehrer registrieren und Lehrerinformationen verwalten',
    'coach-registration': 'Trainer-Registrierung',
    'register-new-coaches': 'Neue Trainer registrieren und Trainerinformationen verwalten'
  },
  
  FRA: {
    // Basic navigation
    'dashboard': 'Tableau de Bord',
    'students': 'Étudiants',
    'teachers-instructors': 'Professeurs & Instructeurs',
    'championships': 'Championnats',
    'administration': 'Administration',
    
    // Common actions
    'new': 'Nouveau',
    'edit': 'Modifier',
    'view': 'Voir',
    'delete': 'Supprimer',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'back': 'Retour',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'export': 'Exporter',
    'import': 'Importer',
    'loading': 'Chargement...',
    'no-data': 'Aucune donnée trouvée',
    'confirm-delete': 'Êtes-vous sûr de vouloir supprimer cet élément?',
    
    // Championship module
    'championship-registration': 'Inscription au Championnat',
    'student-enrollment': 'Inscription des Étudiants aux Championnats',
    'championship-results': 'Résultats du Championnat',
    'ranking-statistics': 'Classement & Statistiques',
    'fight-associations': 'Associations de Combat',
    'affiliations': 'Affiliations',
    'championship-categories': 'Catégories de Championnat',
    'registrations': 'Inscriptions',
    'referees-officials': 'Arbitres / Officiels',
    'championship-sponsors': 'Sponsors du Championnat',
    
    // Common fields
    'name': 'Nom',
    'description': 'Description',
    'date': 'Date',
    'time': 'Heure',
    'location': 'Lieu',
    'contact': 'Contact',
    'email': 'E-mail',
    'phone': 'Téléphone',
    'address': 'Adresse',
    'active': 'Actif',
    'inactive': 'Inactif',
    'all': 'Tous',
    'select': 'Sélectionner',
    'required': 'Requis',
    'optional': 'Optionnel',
    
    // Belt levels
    'white-belt': 'Ceinture Blanche',
    'blue-belt': 'Ceinture Bleue',
    'purple-belt': 'Ceinture Violette',
    'brown-belt': 'Ceinture Marron',
    'black-belt': 'Ceinture Noire',
    
    // Age groups
    'adult': 'Adulte',
    'kids': 'Enfants',
    'master': 'Master',
    'senior': 'Senior',
    
    // Genders
    'male': 'Masculin',
    'female': 'Féminin',
    'other': 'Autre',
    'unisex': 'Unisexe',
    'womens-only': 'Femmes Seulement'
  },
  
  ESP: {
    // Basic navigation
    'dashboard': 'Panel de Control',
    'students': 'Estudiantes',
    'teachers-instructors': 'Profesores e Instructores',
    'championships': 'Campeonatos',
    'administration': 'Administración',
    
    // Common actions
    'new': 'Nuevo',
    'edit': 'Editar',
    'view': 'Ver',
    'delete': 'Eliminar',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'back': 'Volver',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'export': 'Exportar',
    'import': 'Importar',
    'loading': 'Cargando...',
    'no-data': 'No se encontraron datos',
    'confirm-delete': '¿Está seguro de que desea eliminar este elemento?',
    
    // Championship module
    'championship-registration': 'Registro de Campeonato',
    'student-enrollment': 'Inscripción de Estudiantes en Campeonatos',
    'championship-results': 'Resultados del Campeonato',
    'ranking-statistics': 'Ranking y Estadísticas',
    'fight-associations': 'Asociaciones de Lucha',
    'affiliations': 'Afiliaciones',
    'championship-categories': 'Categorías de Campeonato',
    'registrations': 'Inscripciones',
    'referees-officials': 'Árbitros / Oficiales',
    'championship-sponsors': 'Patrocinadores del Campeonato',
    
    // Common fields
    'name': 'Nombre',
    'description': 'Descripción',
    'date': 'Fecha',
    'time': 'Hora',
    'location': 'Ubicación',
    'contact': 'Contacto',
    'email': 'Correo Electrónico',
    'phone': 'Teléfono',
    'address': 'Dirección',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'all': 'Todos',
    'select': 'Seleccionar',
    'required': 'Requerido',
    'optional': 'Opcional',
    
    // Belt levels
    'white-belt': 'Cinturón Blanco',
    'blue-belt': 'Cinturón Azul',
    'purple-belt': 'Cinturón Morado',
    'brown-belt': 'Cinturón Marrón',
    'black-belt': 'Cinturón Negro',
    
    // Age groups
    'adult': 'Adulto',
    'kids': 'Niños',
    'master': 'Master',
    'senior': 'Senior',
    
    // Genders
    'male': 'Masculino',
    'female': 'Femenino',
    'other': 'Otro',
    'unisex': 'Unisex',
    'womens-only': 'Solo Mujeres',
    
    // Teachers page translations
    'teacher-registration': 'Registro de Profesores',
    'register-new-teachers': 'Registrar nuevos profesores y gestionar información de profesores',
    'coach-registration': 'Registro de Entrenadores',
    'register-new-coaches': 'Registrar nuevos entrenadores y gestionar información de entrenadores'
  },
  
  JPN: {
    // Basic navigation
    'dashboard': 'ダッシュボード',
    'students': '学生',
    'teachers-instructors': '教師・インストラクター',
    'championships': '選手権',
    'administration': '管理',
    
    // Common actions
    'new': '新規',
    'edit': '編集',
    'view': '表示',
    'delete': '削除',
    'save': '保存',
    'cancel': 'キャンセル',
    'back': '戻る',
    'search': '検索',
    'filter': 'フィルター',
    'export': 'エクスポート',
    'import': 'インポート',
    'loading': '読み込み中...',
    'no-data': 'データが見つかりません',
    'confirm-delete': 'この項目を削除してもよろしいですか？',
    
    // Championship module
    'championship-registration': '選手権登録',
    'student-enrollment': '学生選手権登録',
    'championship-results': '選手権結果',
    'ranking-statistics': 'ランキング・統計',
    'fight-associations': '格闘技協会',
    'affiliations': '所属',
    'championship-categories': '選手権カテゴリー',
    'registrations': '登録',
    'referees-officials': '審判・役員',
    'championship-sponsors': '選手権スポンサー',
    
    // Common fields
    'name': '名前',
    'description': '説明',
    'date': '日付',
    'time': '時間',
    'location': '場所',
    'contact': '連絡先',
    'email': 'メール',
    'phone': '電話',
    'address': '住所',
    'active': 'アクティブ',
    'inactive': '非アクティブ',
    'all': 'すべて',
    'select': '選択',
    'required': '必須',
    'optional': 'オプション',
    
    // Belt levels
    'white-belt': '白帯',
    'blue-belt': '青帯',
    'purple-belt': '紫帯',
    'brown-belt': '茶帯',
    'black-belt': '黒帯',
    
    // Age groups
    'adult': '大人',
    'kids': '子供',
    'master': 'マスター',
    'senior': 'シニア',
    
    // Genders
    'male': '男性',
    'female': '女性',
    'other': 'その他',
    'unisex': 'ユニセックス',
    'womens-only': '女性のみ',
    
    // Teachers page translations
    'teacher-registration': '教師登録',
    'register-new-teachers': '新しい教師を登録し、教師情報を管理する',
    'coach-registration': 'コーチ登録',
    'register-new-coaches': '新しいコーチを登録し、コーチ情報を管理する'
  },
  
  ITA: {
    // Basic navigation
    'dashboard': 'Dashboard',
    'students': 'Studenti',
    'teachers-instructors': 'Insegnanti e Istruttori',
    'championships': 'Campionati',
    'administration': 'Amministrazione',
    
    // Common actions
    'new': 'Nuovo',
    'edit': 'Modifica',
    'view': 'Visualizza',
    'delete': 'Elimina',
    'save': 'Salva',
    'cancel': 'Annulla',
    'back': 'Indietro',
    'search': 'Cerca',
    'filter': 'Filtra',
    'export': 'Esporta',
    'import': 'Importa',
    'loading': 'Caricamento...',
    'no-data': 'Nessun dato trovato',
    'confirm-delete': 'Sei sicuro di voler eliminare questo elemento?',
    
    // Championship module
    'championship-registration': 'Registrazione Campionato',
    'student-enrollment': 'Iscrizione Studenti ai Campionati',
    'championship-results': 'Risultati Campionato',
    'ranking-statistics': 'Classifica e Statistiche',
    'fight-associations': 'Associazioni di Combattimento',
    'affiliations': 'Affiliazioni',
    'championship-categories': 'Categorie Campionato',
    'registrations': 'Registrazioni',
    'referees-officials': 'Arbitri / Ufficiali',
    'championship-sponsors': 'Sponsor del Campionato',
    
    // Common fields
    'name': 'Nome',
    'description': 'Descrizione',
    'date': 'Data',
    'time': 'Ora',
    'location': 'Posizione',
    'contact': 'Contatto',
    'email': 'Email',
    'phone': 'Telefono',
    'address': 'Indirizzo',
    'active': 'Attivo',
    'inactive': 'Inattivo',
    'all': 'Tutti',
    'select': 'Seleziona',
    'required': 'Richiesto',
    'optional': 'Opzionale',
    
    // Belt levels
    'white-belt': 'Cintura Bianca',
    'blue-belt': 'Cintura Blu',
    'purple-belt': 'Cintura Viola',
    'brown-belt': 'Cintura Marrone',
    'black-belt': 'Cintura Nera',
    
    // Age groups
    'adult': 'Adulti',
    'kids': 'Bambini',
    'master': 'Master',
    'senior': 'Senior',
    
    // Genders
    'male': 'Maschio',
    'female': 'Femmina',
    'other': 'Altro',
    'unisex': 'Unisex',
    'womens-only': 'Solo Donne',
    
    // Teachers page translations
    'teacher-registration': 'Registrazione Insegnanti',
    'register-new-teachers': 'Registra nuovi insegnanti e gestisci informazioni insegnanti',
    'coach-registration': 'Registrazione Allenatori',
    'register-new-coaches': 'Registra nuovi allenatori e gestisci informazioni allenatori'
  },
  
  RUS: {
    // Basic navigation
    'dashboard': 'Панель управления',
    'students': 'Студенты',
    'teachers-instructors': 'Преподаватели и Инструкторы',
    'championships': 'Чемпионаты',
    'administration': 'Администрация',
    
    // Common actions
    'new': 'Новый',
    'edit': 'Редактировать',
    'view': 'Просмотр',
    'delete': 'Удалить',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'back': 'Назад',
    'search': 'Поиск',
    'filter': 'Фильтр',
    'export': 'Экспорт',
    'import': 'Импорт',
    'loading': 'Загрузка...',
    'no-data': 'Данные не найдены',
    'confirm-delete': 'Вы уверены, что хотите удалить этот элемент?',
    
    // Championship module
    'championship-registration': 'Регистрация Чемпионата',
    'student-enrollment': 'Регистрация Студентов в Чемпионатах',
    'championship-results': 'Результаты Чемпионата',
    'ranking-statistics': 'Рейтинг и Статистика',
    'fight-associations': 'Боевые Ассоциации',
    'affiliations': 'Принадлежности',
    'championship-categories': 'Категории Чемпионата',
    'registrations': 'Регистрации',
    'referees-officials': 'Судьи / Официальные лица',
    'championship-sponsors': 'Спонсоры Чемпионата',
    
    // Common fields
    'name': 'Имя',
    'description': 'Описание',
    'date': 'Дата',
    'time': 'Время',
    'location': 'Местоположение',
    'contact': 'Контакт',
    'email': 'Электронная почта',
    'phone': 'Телефон',
    'address': 'Адрес',
    'active': 'Активный',
    'inactive': 'Неактивный',
    'all': 'Все',
    'select': 'Выбрать',
    'required': 'Обязательно',
    'optional': 'Необязательно',
    
    // Belt levels
    'white-belt': 'Белый Пояс',
    'blue-belt': 'Синий Пояс',
    'purple-belt': 'Фиолетовый Пояс',
    'brown-belt': 'Коричневый Пояс',
    'black-belt': 'Черный Пояс',
    
    // Age groups
    'adult': 'Взрослые',
    'kids': 'Дети',
    'master': 'Мастер',
    'senior': 'Сеньор',
    
    // Genders
    'male': 'Мужской',
    'female': 'Женский',
    'other': 'Другой',
    'unisex': 'Унисекс',
    'womens-only': 'Только Женщины',
    
    // Teachers page translations
    'teacher-registration': 'Регистрация Преподавателей',
    'register-new-teachers': 'Зарегистрировать новых преподавателей и управлять информацией преподавателей',
    'coach-registration': 'Регистрация Тренеров',
    'register-new-coaches': 'Зарегистрировать новых тренеров и управлять информацией тренеров'
  },
  
  ARA: {
    // Basic navigation
    'dashboard': 'لوحة التحكم',
    'students': 'الطلاب',
    'teachers-instructors': 'المعلمون والمدرسون',
    'championships': 'البطولات',
    'administration': 'الإدارة',
    
    // Common actions
    'new': 'جديد',
    'edit': 'تعديل',
    'view': 'عرض',
    'delete': 'حذف',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'back': 'رجوع',
    'search': 'بحث',
    'filter': 'تصفية',
    'export': 'تصدير',
    'import': 'استيراد',
    'loading': 'جاري التحميل...',
    'no-data': 'لم يتم العثور على بيانات',
    'confirm-delete': 'هل أنت متأكد من أنك تريد حذف هذا العنصر؟',
    
    // Championship module
    'championship-registration': 'تسجيل البطولة',
    'student-enrollment': 'تسجيل الطلاب في البطولات',
    'championship-results': 'نتائج البطولة',
    'ranking-statistics': 'التصنيف والإحصائيات',
    'fight-associations': 'جمعيات القتال',
    'affiliations': 'الانتماءات',
    'championship-categories': 'فئات البطولة',
    'registrations': 'التسجيلات',
    'referees-officials': 'الحكام / المسؤولون',
    'championship-sponsors': 'رعاة البطولة',
    
    // Common fields
    'name': 'الاسم',
    'description': 'الوصف',
    'date': 'التاريخ',
    'time': 'الوقت',
    'location': 'الموقع',
    'contact': 'جهة الاتصال',
    'email': 'البريد الإلكتروني',
    'phone': 'الهاتف',
    'address': 'العنوان',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'all': 'الكل',
    'select': 'اختيار',
    'required': 'مطلوب',
    'optional': 'اختياري',
    
    // Belt levels
    'white-belt': 'الحزام الأبيض',
    'blue-belt': 'الحزام الأزرق',
    'purple-belt': 'الحزام البنفسجي',
    'brown-belt': 'الحزام البني',
    'black-belt': 'الحزام الأسود',
    
    // Age groups
    'adult': 'البالغون',
    'kids': 'الأطفال',
    'master': 'الماجستير',
    'senior': 'كبار السن',
    
    // Genders
    'male': 'ذكر',
    'female': 'أنثى',
    'other': 'آخر',
    'unisex': 'للجنسين',
    'womens-only': 'للنساء فقط',
    
    // Teachers page translations
    'teacher-registration': 'تسجيل المعلمين',
    'register-new-teachers': 'تسجيل معلمين جدد وإدارة معلومات المعلمين',
    'coach-registration': 'تسجيل المدربين',
    'register-new-coaches': 'تسجيل مدربين جدد وإدارة معلومات المدربين'
  },
  
  KOR: {
    // Basic navigation
    'dashboard': '대시보드',
    'students': '학생',
    'teachers-instructors': '교사 및 강사',
    'championships': '챔피언십',
    'administration': '관리',
    
    // Common actions
    'new': '새로 만들기',
    'edit': '편집',
    'view': '보기',
    'delete': '삭제',
    'save': '저장',
    'cancel': '취소',
    'back': '뒤로',
    'search': '검색',
    'filter': '필터',
    'export': '내보내기',
    'import': '가져오기',
    'loading': '로딩 중...',
    'no-data': '데이터를 찾을 수 없습니다',
    'confirm-delete': '이 항목을 삭제하시겠습니까?',
    
    // Championship module
    'championship-registration': '챔피언십 등록',
    'student-enrollment': '학생 챔피언십 등록',
    'championship-results': '챔피언십 결과',
    'ranking-statistics': '순위 및 통계',
    'fight-associations': '격투 협회',
    'affiliations': '소속',
    'championship-categories': '챔피언십 카테고리',
    'registrations': '등록',
    'referees-officials': '심판 / 공무원',
    'championship-sponsors': '챔피언십 스폰서',
    
    // Common fields
    'name': '이름',
    'description': '설명',
    'date': '날짜',
    'time': '시간',
    'location': '위치',
    'contact': '연락처',
    'email': '이메일',
    'phone': '전화',
    'address': '주소',
    'active': '활성',
    'inactive': '비활성',
    'all': '모두',
    'select': '선택',
    'required': '필수',
    'optional': '선택사항',
    
    // Belt levels
    'white-belt': '흰색 벨트',
    'blue-belt': '파란색 벨트',
    'purple-belt': '보라색 벨트',
    'brown-belt': '갈색 벨트',
    'black-belt': '검은색 벨트',
    
    // Age groups
    'adult': '성인',
    'kids': '어린이',
    'master': '마스터',
    'senior': '시니어',
    
    // Genders
    'male': '남성',
    'female': '여성',
    'other': '기타',
    'unisex': '유니섹스',
    'womens-only': '여성 전용',
    
    // Teachers page translations
    'teacher-registration': '교사 등록',
    'register-new-teachers': '새 교사를 등록하고 교사 정보를 관리합니다',
    'coach-registration': '코치 등록',
    'register-new-coaches': '새 코치를 등록하고 코치 정보를 관리합니다'
  }
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('PTB')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && ['ENU', 'PTB', 'GER', 'FRA', 'ESP', 'JPN', 'ITA', 'RUS', 'ARA', 'KOR'].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string): string => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}